### ISSUE TITLE
Justified Gallery cutting heads off in mobile

### ISSUE THREAD

**Issue by ekerner-com** [miromannino/Justified-Gallery#103]
As per subject.

Example screenshot at 
 http://ekerner.com/download/justified-gallery-cutting-heads-off-in-mobile.jpg

Working example while it lasts (tmp dev site) at 
 http://ihaveseen.wrcbeta.co.uk/weddings/wedding01

Thanks and kind regards,
Eugene.

**Comment by miromannino** [comment]
Hi @ekerner-com. Good news for you, the fix is simple: upgrade to the version 3.6. Tell me if that's all ok.

Best regards,
Miro

**Comment by ekerner-com** [comment]
That fixed the head overflowing issue thanks, however it made my first image large and I cant for the life of me work out how to stop it. Iv looked thru the examples and cant see what tells it that the first image should be large or not :(

**Comment by ekerner-com** [comment]
Still trying to work it out. 
If I make the rowHeight 400 then the first image takes full width, see http://ihaveseen.wrcbeta.co.uk/weddings
If I make the rowHeight 300 then it works as normal. http://ihaveseen.wrcbeta.co.uk/personal
Currently viewing in FireFox at 1366 x 768px screen resolution if that helps.
Any clues?

**Comment by miromannino** [comment]
Oh yes, 400 is very big as height... 

For example, in my 1280 screen, the available space for the gallery is 1180. If you choose the gallery height to be 400px, it means that it tries to resize the images to have that height.
The first image is 1024x683, and resized is 602x400. If the gallery tries to have two images in the first row, the space will be more than 1204 (and more because there is the margin). This means that the images are splitted into two rows, and the first image becomes very big.

To resume, the height that you specifiy is like a minimum height that you want for your gallery.

- You simply have to reduce it to something like 300px.

- You can also specify the maximum height (but it will crop the images).

- You can also listen the page width to change the gallery height in real time (for this thing I'm going to do an example in the documentation).

**Comment by ekerner-com** [comment]
Thanks for your explanation, however I believe I have some valid arguments :) ...
If the above is true then why do the subsequent rows render as expected?
The above presumes that the image are 6:4 ish landscape, while there could be portrait and square images in the mix.
My current screen is 1920x1080, not an uncommon or large size these days, and 400px height isnt unreasonable.

Incidentally, the gallery with rowHeight set to 300px has set the first row images (2 x landscape 6:4 ) height to 410px, AND 
the gallery with rowHeight set to 400px has done the same for the rows succeeding the first large image, the only diff being that the rowHeight 400 gallery has a large first image.

I love the way the gallery handles screen resizing and orientation changes and I feel no need to adjust the row heights as you describe in my case.

That all being said JG is a very elegant solution to a quite complex problem, so thanks :)
Plus, Iv employed the large first image thing to showcase the photographers latest project and he loves it.

My opinion ...
largeFirstImage (called whatever) should be an option.
Unless my invented largeFirstImage option is set then the first image should not be larger based on rowHeight UNLESS the row height causes the first image to exceed the justifyThreshold.

Love your work!

**Comment by miromannino** [comment]
I inspected the reasons why the first image is always bigger and alone. That first image effect is not because it is the first, but is because the next image is a landscape image too, so putting two landscape images would require a row height that is less than 400px, and for this reason they are splitted in two row (and the first becomes very big).

So the only things that we can do are:

1) you could reorder your images to have your second image in the third position (so a portrait image will be put in the first row)

2) I can allow the row to be less than the rowHeight. Sometimes it could be a kind of a bug, but It would have also a good appeal. 

for now just reorder the images if you can, I will modify JG to allow this kind of feature (but that thing is a little bit delicate).

Thank you

**Comment by ekerner-com** [comment]
Im happy with it as-is, it was just a suggestion :)
Thanks for everything!!
