### ISSUE TITLE
Photos not showing at all

### ISSUE THREAD

**Issue by woodylo** [miromannino/Justified-Gallery#119]
I used to have the Flickr Photostream (outdated) plugin which worked fine. Now I'm trying to use the up-to-date Flickr Justified Gallery plugin but it doesn't work at all.

WordPress 4.3.1 running Fashionistas theme.
Flickr Justified Gallery version 3.4.0.

No error in console but in the source code there is no height at all! On other websites there is height.
![screenshot 2015-09-18 a 10 53 25](https://cloud.githubusercontent.com/assets/14344701/9955713/89600808-5df3-11e5-91a2-a6981404eda5.jpg)

I have changed theme, I have deactivated all the plugins except FJG, tried to change all of the FJG settings.. nothing helped!

Link: http://www.dailyfashionstyle.com/pfw-agnes-b-ss-2015

Thanks a lot in advance.

**Comment by miromannino** [comment]
Seems that all works fine now, right?
Thank you

**Comment by miromannino** [comment]
I don't know what plugins do that, but all the scripts have the text/rocketscript type. I don't know why it do that, but seems that plugin that doesn't allow the scripts to be loaded. In fact, if I try to copy and paste all the scripts in the page (that probably wasn't loaded and/or executed) the gallery appears.

**Comment by woodylo** [comment]
Hi again! Thanks for your time.
I have deactivated the rocketscript (due to Cloudflare). You may see there
is a javascript problem in the console. I did everything to see where it
could come from: changing theme, deactivating all of the plugins... it
still remained.

*Laurent Dubois*
+33 6 12 33 09 64

2015-09-18 16:03 GMT+02:00 Miro Mannino <notifications@github.com>:

**Comment by miromannino** [comment]
Have you tried to remove the lookbook? Seems that that thing does strange things reloading jquery.

**Comment by woodylo** [comment]
that was it. You're awesome!! How did you manage to see that the lookbook
thing was messing everything?

*Laurent Dubois*
+33 6 12 33 09 64

2015-09-18 17:12 GMT+02:00 Miro Mannino <notifications@github.com>:

**Comment by miromannino** [comment]
I don't know, maybe just experience or my instinct. I didn't know that was it for sure because I haven't tried to change the page to see what would happen.

For sure that sidebar/plugin/everything must load jquery using the correct wordpress functions. In this way that is not correct.

As I said also in other issues: 
_Since I'm working on this project for free during my midnights, please consider to share or star this plugin. Moreover, consider to add me on LinkedIn (Miro Mannino) to endorse me some skills or to leave me a positive comment, or just to connect each other in case of future projects together. I don't want donations, I just would to be recognised for my works. Thank you_
