### ISSUE TITLE
add filter and sort functions

### ISSUE THREAD

**Issue by pattycam** [miromannino/Justified-Gallery#33]
add filter and sort functions

**Comment by jaidev** [comment]
+1 - currently, we apply filters by hiding the images (so that we don't have to refresh the entire set). however, there is no way to tell justified gallery to ignore pictures that are hidden and to re-arrange

**Comment by robhadfield** [comment]
^ I'm doing the exact same thing. Te only way I can do it is to remove them from the dom altogether which makes it a bit heavy handed.

A way to ignore a particular selector would be great!

**Comment by klihelp** [comment]
+

**Comment by DavidKroutArt** [comment]
klihelp, maybe it just didn't help me but the forks didn't work very well. 

This is the best thing working for me so far. The spinner thing doesn't reload and kind of messes my stuff up. The other two ways, hiding and displaying none semi-works but I can't justify the gallery. When I load it at the end either nothing happens or the spinner just breaks it.

Is there a way to fix this or am I doing something wrong?

$('.btn_photo').on('click', function(event) {
//$('.anim, .cinema, .graph, .web').addClass('spinner'); 
//$('.photo').removeClass('spinner'); 
$('.photo').css('display','block');

$('.anim, .web, .cinema, .graph').css('display','none');
$('.anim, .web, .cinema, .graph').hide();

//$("#gallery").justifiedGallery();
});

Either the spanners reload incorrectly and it cannot be justified after hiding / adding a spinner class, or my other two ways of hiding and displaying none just make the images not show up, but the justifying keeps it from showing up which is why I've currently commented it out.

Does anyone know how to fix it? I'm trying to get buttons show and hide pictures or divs.

**Comment by DavidKroutArt** [comment]
Also, I can't seem to figure out why, and I think it is the jquery doing it, my images keep adding 1 to the top and left. I have taken out padding, matting, and any other number so that my images would hopefully stay together.

**Comment by robhadfield** [comment]
I think your first issue is what I described above - the elements need to be removed altogether, not just hidden. This causes issues.

The second issue sounds like margins - have you tried removing the margins in your options?

    $("#gallery").justifiedGallery({ 'margins' : false });

**Comment by robhadfield** [comment]
@klihelp - Thanks I'll try that branch, I hadn't spotted that.

**Comment by klihelp** [comment]
I have found a full custom project, I believe it's a fork of this plugin, which does double filtering and sorting:

http://justifiedgrid.com/

**Comment by miromannino** [comment]
OK, you convinced me, I'm doing it. ;)

**Comment by robhadfield** [comment]
That would be awesome @miromannino :dancers:

**Comment by DavidKroutArt** [comment]
+1, 

When it is up I'm certainly giving credit in the About section, and advertising it on social media ends. 

In my mind you'd have the best plugin around. I already like it a lot, but it doesn't allow me to have five categories, yet. I've searched top jquery, jquery grids, and a bunch of other stuff for a straight three days. Honestly, yours is the best I've seen so far. Adding in a way to filter would just be amazing.

http://davidkrout.com/ is all I've got now.. 
http://davidkrout.com/justified/ is my attempt with Justifiedgallery, which looks much better. 
Although, I'll have to try that way to get the margins off. 

I'll probably switch back to justified and "move on" until there is a way I can sort. I just want to get rid of my "dummy images". 

Best of luck to you Mr. Miromannino! I'll keep an eye out. :)

**Comment by DavidKroutArt** [comment]
@robhadfield I think he might have fixed it in the JS file, I just redownloaded everything. I just changed margins : 1, to margins : 0, at the start, which I'm sure I would have done the first time, since I did edit a lot.. That fixed everything!  

I still hope @miromannino works on the filter / sorting bit, but I'll just keep supporting the product and using it regardless, since he seems interested in his consumers, which is always an amazing sign.

I'd like to talk about donating a bit, but that will have to happen when I get a job. :/

**Comment by miromannino** [comment]
Thanks @DavidKroutArt. I'm implementing it in those days.

**Comment by miromannino** [comment]
Thanks all for your help and your ideas. This feature will be available in 3.6 (and you can try it in 3.6 branch now, but without documentation for now). 

Since I'm working on this project for free during the midnight for a week.
Please consider to add me on LinkedIn to endorse me some skills or to leave me a positive comment. I don't want donations, just your acknowledgement for my work. Thanks

**Comment by robhadfield** [comment]
No problem at all Miro - I've sent you a connection request. Thanks.

**Comment by miromannino** [comment]
Are wise people like you that make people truly happy, and keep the technology to go forward. Thank you Rob

**Comment by robhadfield** [comment]
:+1:

**Comment by tmconnect** [comment]
Thanks Miro for this great new functions.

I tested the filtering and it works great. The only thing, that I didn't like, is the reordering of the images using a filter and than go back to no-filter. The previously filtered images are at the end of the grid after going back to no-filter.

Hope you can change this, so the images are in the order as they are on page load.

Thanks
Thomas

**Comment by miromannino** [comment]
Yep, since the comparator says that some images are equal it could reorder it (it depends on the JS sorting algorithm). But I think it can be solved.

**Comment by miromannino** [comment]
@tmconnect now it work without the problem you mentioned. 

Thanks
Miro
