### ISSUE TITLE
Captions not working

### ISSUE THREAD

**Issue by jefftucker1952** [miromannino/Justified-Gallery#330]
Captions in 3.8.1 are not working. Compare these two pages - the only difference between them is the version of JG:

https://jefftucker.net/JGcaptions370/

https://jefftucker.net/JGcaptions381/

The captions appear on mouseover in 3.7.0, but not in 3.8.1.

**Comment by jefftucker1952** [comment]
A little hunting in the source code reveals what I believe is the solution:

`<div class='jg-caption'>The Caption</div>`

Have I got that right? Does anything else have to be changed?

A sensible change, since a class of just **caption** is pretty generic.

**Comment by miromannino** [comment]
Yes exactly, not anymore caption, but jg-caption. It was renamed because it's likely that the beginners are going to have CSS that is polluting all elements with class caption, so they cause bugs on JG. It'a already in the list of changes, but I'll change also the documentation for this.

Thank you for mentioning
