### ISSUE TITLE
Adding text to gallery

### ISSUE THREAD

**Issue by DenBeke** [miromannino/Justified-Gallery#69]
Is there any possibility to add text to a gallery, in a way that it will be handled as an image?
I mean that when you add a small or large paragraph, the text container will accordingly scale. Or is that just impossible?

I already managed to put text in to it, but sometimes the text is too large to fit the 'gap'. (the following is an example where the text is **not** too large...)
![schermafbeelding 2015-01-15 om 19 16 51](https://cloud.githubusercontent.com/assets/3856745/5763504/1f69d2d6-9ceb-11e4-8bfc-3725f7a20d67.png)

Thanks in advance!

**Comment by klihelp** [comment]
+ 1 for this.
I managed to do it by having a transparent image in the text-div

**Comment by miromannino** [comment]
I love it! I'm doing it.
Thanks @klihelp for the temporary workaroung

**Comment by DenBeke** [comment]
Thank you, @miromannino!

**Comment by miromannino** [comment]
Done in 3.6
@DenBeke I would like to see your beautiful gallery with texts in action. give me a link when you have it.

_If this project is useful for you and since I'm working on it for free during my midnights, please take few minutes to contribute to this project in some way. Star this project on github, share it, or recognise my work adding me on LinkedIn (Miro Mannino) to endorse me some skills, to leave me a positive comment, or just to connect each other in case of future projects together. Thank you_

**Comment by DenBeke** [comment]
Thank you @miromannino.
I will not have time to show it off the first month. But later I'll work again on an older project and give you a show case :)

**Comment by klihelp** [comment]
Would love to try this soon, curious how the text box width/height and overflow for longer text is working.

**Comment by tomkeysers** [comment]
Lovely feature! Trying to make it work, but can't get to it... This is what I get:
![printscreen](http://image.prntscr.com/image/1107a0a8297e436981ec043c88023570.png)

How can I make sure the text will not take a full row, but rather a box?

**Comment by klihelp** [comment]
@tomkeysers 
Insert a transparent image in the text-div, that image dimension gives the frame

**Comment by tomkeysers** [comment]
Should have checked the docs better... it's all [in there](http://miromannino.github.io/Justified-Gallery/input-formats/). 
Thanks anyway @klihelp !
