### ISSUE TITLE
Broken Image Links

### ISSUE THREAD

**Issue by ttseng** [miromannino/Justified-Gallery#76]
I am using Justified-Gallery in my Rails app and keep running into issues with broken image links.  They are sometimes fixed when the browser window is resized or if I reinitiate justifiedGallery.  Nonetheless, I receive a lot of console error messages when loading the page because it's looking for thumbnails that don't exist.  

You can check out an example here:

http://buildinprogress.media.mit.edu/projects/2213/gallery

Do you have any suggestions for how to fix this?

**Comment by miromannino** [comment]
The problem seems related to the additional thumbnails that you don't have. Probably this is because you haven't read the documentation, and I understand that.

For this reason I changed the default settings, to avoid these errors in 3.5+. Please update to that version, and tell me if it works well.

**Comment by ttseng** [comment]
Thanks - your update fixes the problem for me!
