### ISSUE TITLE
.destroy() #feature-request

### ISSUE THREAD

**Issue by danielschmid** [miromannino/Justified-Gallery#90]
The ability to destroy an instance would be very useful for responsive layouts.

**Comment by klihelp** [comment]
+1

**Comment by miromannino** [comment]
From 3.6 is possible to call `$("#myGallery").justifiedGallery('destroy')`. I don't know if you preferred a specific destroy method like `$("#myGallery").destroy()`, but seems that all the jQuery plugins call methods passing the name of the method as argument to the main plugin function. Tell me if you had different ideas, or if it is possible to do something more.

**Comment by robhadfield** [comment]
I think that's the current syntax Miro - I noticed that slick.js (another of my favourite plugins) follow this method now.

**Comment by danielschmid** [comment]
`$("#myGallery").justifiedGallery('destroy')`
Couldnt test it yet but looks fine for me. thanks.

**Comment by miromannino** [comment]
Yes you could clone the 3.6 branch now. I will release the final version in a couple of days.

As I said also in other issues: 
Since I'm working on this project for free during my midnights, please consider to add me on LinkedIn (Miro Mannino) to endorse me some skills or to leave me a positive comment, or just to connect each other in case of future projects together. I don't want donations, I just would to be recognised for my works. Thank you
