### ISSUE TITLE
Force Same Image Size In Mobile

### ISSUE THREAD

**Issue by sprywebtech** [miromannino/Justified-Gallery#99]
How do I force all images to be same size and stack in responsive/mobile view. The last two images resize and sit side by side and I need them to all stay same size and can't find where to change that. Thanks for any help  you can provide. 

page - http://webclient.co/pacifica/our-leadership/

![responsive-grid-wp-support](https://cloud.githubusercontent.com/assets/8998526/8298777/67325b9e-1976-11e5-86c1-c0ef3ae3d8bc.JPG)

**Comment by miromannino** [comment]
OK, this has been fixed and will be available in 3.6.
This i the settings I suggest you to use in this situation 
`{ lastRow: 'nojustify', justifyThreshold: 0.5}`

_If this project is useful for you and since I'm working on it for free during my midnights, please take few minutes to contribute to this project in some way. Star this project on github, share it, or recognise my work adding me on LinkedIn (Miro Mannino) to endorse me some skills, to leave me a positive comment, or just to connect each other in case of future projects together. Thank you_
